version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing dependences
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/* && apt-get install -y gcc && apt-get install cmake'
      - run:
          name: Configuring build environment
          command: 'cmake CMakeLists.txt -Bbuild'
      - run:
          name: Building project
          command: 'cmake --build build'